name: test-gh-security-workflow
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

on:
  push:
    branches:
      - '**'
jobs:
  build:
    steps:
    - name: checkout-source-code.
      uses: cloudbees-io/checkout@v1
    - name: gh-security.
      uses: cloudbees-io/github-security-scanner
      with:
        token: ${{ secrets.GITHUB_SECURITY_PAT_BANKA }}
        language: "LANGUAGE_GO"
        gitAccessToken: ${{ secrets.GITHUB_SECURITY_PAT_BANKA }}